### ISSUE TITLE
sad panda: "vxdocker run ubuntu ls -la" did nothing

### ISSUE THREAD

**Issue by drnic** [websecurify/node-vxdocker#1]
```
$  sudo npm install -g vxdocker
...
vxdocker@0.0.2 /usr/local/lib/node_modules/vxdocker
├── portchecker@0.1.2
├── logsmith@0.0.2 (winston@0.7.2)
└── vortex@0.9.20 (progress2@0.1.1, path-extra@0.1.1, async@0.2.9, node-getopt@0.2.3, vboxmanage@0.0.12, aws-sdk@1.4.0, roost@0.6.14)
➜  ~  vxdocker images
➜  ~  vxdocker run ubuntu ls -la
```

![sad-panda](https://f.cloud.github.com/assets/108/1093591/ca497aa4-16a4-11e3-9837-fed9652f9076.jpg)

**Comment by drnic** [comment]
```
➜  ~  node -v
v0.10.12
➜  ~  VBoxManage -v
4.2.12r84980
```

**Comment by drnic** [comment]
I don't think I know how to use computers anymore:

```
➜  ~  vxdocker -h
➜  ~  vxdocker   
➜  ~  vxdocker -v
```

**Comment by rberger** [comment]
Heh, I'm in the same place as Dr.Nic. If he's having problems I'm not so embarrased to note that I can't make it work!

I presume there is some missing incantations to get vxdocker connected to virtualbox/a running docker in virtualbox or something along those lines. It is a bit disconcerting that no mater what command you give to vxdocker it does nothing and gives no usage or error message. 

I applaud you folks creating this software. I'm sure it works great, but we could use a bit help understanding how to use it.

Thanks!

```
node -v
v0.10.18

VBoxManage -v
4.2.18r88780
```

```
➜ ~ vxdocker -h
➜ ~ vxdocker --help
➜ ~ vxdocker help
```

**Comment by rberger** [comment]
Would like to also request a bit of instructions on how to run it within a cloned repo of the code.

FYI running Mac OSX 10.8 with node/npm installed by an up to date homebrew

Not being node savy I tried the obvious and it doesn't work:

```
 ./bin/vxdocker

module.js:340
    throw err;
          ^
Error: Cannot find module 'vortex'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/rberger/work/docker/node-vxdocker/lib/vortex.js:2:14)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```

**Comment by rberger** [comment]
So I think one problem might be that
`https://s3.amazonaws.com/node-vortex/precise64-docker.ova`
is not accessible by the public. And vxdocker fails silently when it can't fetch this file.

I hacked `/usr/local/share/npm/lib/node-modules/vxdocker/lib/command.js` to change the loglevel to debug and then re-ran `vxdocker images` and saw:

```
vxdocker images
verbose: exec /Applications/VirtualBox.app/Contents/MacOS/VBoxManage showvminfo vxdocker:docker --machinereadable
VBoxManage: error: Could not find a registered machine named 'vxdocker:docker'
VBoxManage: error: Details: code VBOX_E_OBJECT_NOT_FOUND (0x80bb0001), component VirtualBox, interface IVirtualBox, callee nsISupports
VBoxManage: error: Context: "FindMachine(Bstr(VMNameOrUuid).raw(), machine.asOutParam())" at line 2495 of file VBoxManageInfo.cpp
verbose: exec /Applications/VirtualBox.app/Contents/MacOS/VBoxManage guestproperty enumerate vxdocker:docker
VBoxManage: error: Could not find a registered machine named 'vxdocker:docker'
VBoxManage: error: Details: code VBOX_E_OBJECT_NOT_FOUND (0x80bb0001), component VirtualBox, interface IVirtualBox, callee nsISupports
VBoxManage: error: Context: "FindMachine(Bstr(a->argv[0]).raw(), machine.asOutParam())" at line 211 of file VBoxManageGuestProp.cpp
verbose: exec /Applications/VirtualBox.app/Contents/MacOS/VBoxManage showvminfo vxdocker:docker --machinereadable
VBoxManage: error: Could not find a registered machine named 'vxdocker:docker'
VBoxManage: error: Details: code VBOX_E_OBJECT_NOT_FOUND (0x80bb0001), component VirtualBox, interface IVirtualBox, callee nsISupports
VBoxManage: error: Context: "FindMachine(Bstr(VMNameOrUuid).raw(), machine.asOutParam())" at line 2495 of file VBoxManageInfo.cpp
verbose: exec /Applications/VirtualBox.app/Contents/MacOS/VBoxManage guestproperty enumerate vxdocker:docker
VBoxManage: error: Could not find a registered machine named 'vxdocker:docker'
VBoxManage: error: Details: code VBOX_E_OBJECT_NOT_FOUND (0x80bb0001), component VirtualBox, interface IVirtualBox, callee nsISupports
VBoxManage: error: Context: "FindMachine(Bstr(a->argv[0]).raw(), machine.asOutParam())" at line 211 of file VBoxManageGuestProp.cpp
verbose: exec /Applications/VirtualBox.app/Contents/MacOS/VBoxManage unregistervm vxdocker:docker --delete
VBoxManage: error: Could not find a registered machine named 'vxdocker:docker'
VBoxManage: error: Details: code VBOX_E_OBJECT_NOT_FOUND (0x80bb0001), component VirtualBox, interface IVirtualBox, callee nsISupports
VBoxManage: error: Context: "FindMachine(Bstr(VMName).raw(), machine.asOutParam())" at line 156 of file VBoxManageMisc.cpp
debug: cannot remove vxdocker:docker
verbose: exec /Applications/VirtualBox.app/Contents/MacOS/VBoxManage showvminfo precise64-docker --machinereadable
VBoxManage: error: Could not find a registered machine named 'precise64-docker'
VBoxManage: error: Details: code VBOX_E_OBJECT_NOT_FOUND (0x80bb0001), component VirtualBox, interface IVirtualBox, callee nsISupports
VBoxManage: error: Context: "FindMachine(Bstr(VMNameOrUuid).raw(), machine.asOutParam())" at line 2495 of file VBoxManageInfo.cpp
debug: cannot show vm info for precise64-docker
debug: import "https://s3.amazonaws.com/node-vortex/precise64-docker.ova" into "precise64-docker"
verbose: download "https://s3.amazonaws.com/node-vortex/precise64-docker.ova" to "/tmp/1378710285159-precise64-docker.ova"
```

So then I tried to use the vortex example `node-vortex/doc/examples/docker-helloworld` which seemed to do the same inner work of vxworker (the last few lines of the debug output) and got this:

```
vortex boot
error: not allowed to download "https://s3.amazonaws.com/node-vortex/precise64-docker.ova"
```

I tried accessing `https://s3.amazonaws.com/node-vortex/precise64-docker.ova` from my browser and got:

``` xml
<Error>
  <Code>AccessDenied</Code>
  <Message>Access Denied</Message>
  <RequestId>E08BADD6FA76A891</RequestId>
  <HostId>
    WckGpW8jYWsf4bDGQEEDT3Sw+yoRC0hWiXeHZp1JxIu7nrYiZ1Q4zn6piIBKy17J
  </HostId>
</Error>
```

**Comment by websecurify** [comment]
Thanks for the awesome feedback both of you.

That is need the case. For some reason the permissions on that file got borked. This should be fixed now. Just keep in mind that the first time you boot the instance it will be painfully slow because this file needs to be downloaded. The current version does not expose a progress bar in a nice way. When we move to the new version of Vortex, the indicator will be there. Hopefully we will be able to complete this work by the end of the week.

We will keep this issue open until we find out if it has been fixed for you.

Regards.
